baseURL = "https://dante-sans-virgil.com/"
languageCode = "en-us"
title = "Dante sans Virgil: A Wandering Project Blog"
theme = "PaperMod"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
